name: hello world integração

on: 
  push:
    branches: ("main")
  pull_request: 
    branches: ("main")

jobs: 
  olaMundo: 
    runs-on: ubunto-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Diga
        run: echo Hello-docker
